### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by dosumis** [brain-bican/taxonomy-development-tools#46]
The current navigation workflows are quite slow and clunky.  Even with prior knowledge of terms used and taxonomy structure, navigation is tricky. 

This EPIC aims to collect suggestions for improving navigation, which we can then prioritise.

- [ ] Default for single column refine should be 'in' (regex  wildcard are more advanced options).
- [ ] Add a global refine that works across all columns, with refinement working as you type. SImple text refine would be a big improvement.  Even better I think is the original iTunes functionality:  It treated separate words as two separate refines - allowing multi-column refinement.
- [ ] Hyperlinked navigation on taxonomy tree - refine column to selected term (right click option to refine to all with selected term as parent cell set?)
- [ ] Hyperlinked navigation on parent cell sets - click on parent cell set, refine to term (right click open to refine to all with this parent cell set?
